excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://brehonio.github.io
title: Brehon Arbitration Protocol
tagline: A third party arbitration protocol for smart contracts
description: A third party arbitration protocol for smart contracts
paginate: 5